[workspace]
members = ["joerl", "joerl_macro"]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2024"
authors = ["Aleksei Matiushkin <am@ambment.cat>"]
license = "MIT"
repository = "https://github.com/am-kantox/joerl"
